"""
F08 & F08.1 — View Traceability & View Product History
Test Design Reference: SOFTEST-TEST-DESIGN.md (TC-08-001 → TC-08-006)

Navigation note: The app exposes traceability via /verify/{batchId} (URL-based).
Tests reach the page by navigating directly to that URL — the "batch ID entry path"
described in the test design (as opposed to QR code scanning).

Usage:
    cd testing/scripts
    ./run_tests.sh -k "f08"                     # bash — headless
    ./run_tests.sh --headed -k "f08"            # bash — headed (WSLg)
    ./run_tests.sh --headed --keep-open -k "f08"
    .\\run_f08.ps1                              # PowerShell (Windows)
    .\\run_f08.ps1 --headed                     # PowerShell headed

Prerequisites:
  - Frontend at http://localhost:3001
  - Backend  at http://localhost:3000
  - Set VALID_BATCH_ID and INCOMPLETE_BATCH_ID below to real values from your DB:
      SELECT id FROM "Batch" WHERE status = 'SOLD' LIMIT 1;        -- complete
      SELECT id FROM "Batch" WHERE status = 'HARVESTED' LIMIT 1;   -- incomplete
"""

import json
import os
import time
import urllib.parse

import pytest
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

from conftest import BASE_URL, login_as_retailer

# ─────────────────────────────────────────────────────────────
#  BATCH IDs — loaded automatically from batch_ids.json
#  (generated by:  node seed_test_data.js)
#
#  If the file is missing, fall back to the hardcoded values
#  below and update them manually.
# ─────────────────────────────────────────────────────────────
def _load_batch_ids():
    json_path = os.path.join(os.path.dirname(__file__), "batch_ids.json")
    if os.path.exists(json_path):
        with open(json_path) as f:
            data = json.load(f)
        valid      = data.get("VALID_BATCH_ID",      "REPLACE_WITH_VALID_BATCH_ID")
        incomplete = data.get("INCOMPLETE_BATCH_ID",  "REPLACE_WITH_INCOMPLETE_BATCH_ID")
        print(f"\n[seed] Loaded batch IDs from batch_ids.json")
        print(f"       VALID_BATCH_ID:      {valid}")
        print(f"       INCOMPLETE_BATCH_ID: {incomplete}")
        return valid, incomplete
    return "REPLACE_WITH_VALID_BATCH_ID", "REPLACE_WITH_INCOMPLETE_BATCH_ID"


VALID_BATCH_ID, INCOMPLETE_BATCH_ID = _load_batch_ids()

WAIT = 15
# ─────────────────────────────────────────────────────────────


def _url(batch_id: str) -> str:
    return f"{BASE_URL}/verify/{urllib.parse.quote(str(batch_id), safe='')}"


def _wait_load(driver, timeout=WAIT):
    """Block until the loading spinner disappears."""
    try:
        WebDriverWait(driver, timeout).until(
            EC.invisibility_of_element_located((By.CSS_SELECTOR, ".animate-spin"))
        )
    except TimeoutException:
        pass


def _find(driver, xpath, timeout=WAIT):
    return WebDriverWait(driver, timeout).until(
        EC.presence_of_element_located((By.XPATH, xpath))
    )


# ═════════════════════════════════════════════════════════════
#  TC-08-001: Verify Traceability View with Valid Batch ID
#  TCOV: 08-001, 08-005, 08-010, 08-011, 08-012, 08-013, 08-014, 08-017
# ═════════════════════════════════════════════════════════════
class TestTC08001:
    """
    Pre-conditions : Logged in as Retailer; VALID_BATCH_ID has complete supply chain.
    Post-conditions: Full product history timeline rendered with all stages and
                     blockchain verification status visible.
    """

    @pytest.fixture(autouse=True)
    def setup(self, driver):
        self.d = driver

    def test_page_loads_after_valid_batch_id(self):
        """Navigate to /verify/VALID_BATCH_ID — page must finish loading."""
        login_as_retailer(self.d)
        self.d.get(_url(VALID_BATCH_ID))
        _wait_load(self.d)

        loaded = WebDriverWait(self.d, WAIT).until(
            lambda d: d.find_elements(By.CSS_SELECTOR, "h1, h2")
        )
        assert loaded, "Page did not finish loading — no heading found"

    def test_product_history_timeline_displayed(self):
        """TCON-08-010: 'Supply Chain Journey' section is visible."""
        login_as_retailer(self.d)
        self.d.get(_url(VALID_BATCH_ID))
        _wait_load(self.d)

        el = _find(self.d, "//*[contains(text(),'Supply Chain Journey')]")
        assert el.is_displayed(), "Supply Chain Journey (timeline) is not visible"

    def test_farmer_info_section_visible(self):
        """TCON-08-011: Origin Farm Information section is visible."""
        login_as_retailer(self.d)
        self.d.get(_url(VALID_BATCH_ID))
        _wait_load(self.d)

        el = _find(self.d, "//*[contains(text(),'Origin Farm Information')]")
        assert el.is_displayed(), "Origin Farm Information section is not visible"

    def test_processing_stage_visible_in_timeline(self):
        """TCON-08-012: Processing stage visible inside Supply Chain Journey."""
        login_as_retailer(self.d)
        self.d.get(_url(VALID_BATCH_ID))
        _wait_load(self.d)

        el = _find(self.d, "//*[contains(text(),'Processing') or contains(text(),'Processor')]")
        assert el.is_displayed(), "Processing stage not visible in timeline"

    def test_distribution_stage_visible_in_timeline(self):
        """TCON-08-013: Distribution stage visible inside Supply Chain Journey."""
        login_as_retailer(self.d)
        self.d.get(_url(VALID_BATCH_ID))
        _wait_load(self.d)

        el = _find(self.d, "//*[contains(text(),'Distribution') or contains(text(),'Distributor')]")
        assert el.is_displayed(), "Distribution stage not visible in timeline"

    def test_blockchain_verification_status_displayed(self):
        """TCON-08-014: Blockchain verification status visible on the page."""
        login_as_retailer(self.d)
        self.d.get(_url(VALID_BATCH_ID))
        _wait_load(self.d)

        el = _find(self.d, "//*[contains(text(),'Blockchain Verified') or contains(text(),'Blockchain')]")
        assert el.is_displayed(), "Blockchain verification status not visible"


# ═════════════════════════════════════════════════════════════
#  TC-08-002: Verify Non-Existent or Invalid Batch ID
#  TCOV: 08-002, 08-004, 08-018
# ═════════════════════════════════════════════════════════════
class TestTC08002:
    """
    Pre-conditions : User is on the traceability page (no login required).
    Post-conditions: No timeline rendered; error message displayed.
    """

    @pytest.fixture(autouse=True)
    def setup(self, driver):
        self.d = driver

    def test_non_existent_batch_shows_error(self):
        """TCON-08-002: 'Verification Failed' shown for non-existent batch ID."""
        self.d.get(_url("BATCH-99999"))
        _wait_load(self.d)

        el = _find(self.d, "//*[contains(text(),'Verification Failed')]")
        assert el.is_displayed(), "Error message not shown for non-existent batch ID"

    def test_non_existent_batch_no_timeline(self):
        """TCON-08-018: No timeline rendered for non-existent batch."""
        self.d.get(_url("BATCH-99999"))
        _wait_load(self.d)

        timeline = self.d.find_elements(By.XPATH, "//*[contains(text(),'Supply Chain Journey')]")
        assert len(timeline) == 0, "Timeline must NOT appear for a non-existent batch ID"

    def test_invalid_format_batch_shows_error(self):
        """TCON-08-004: Invalid-character batch ID shows error, no timeline."""
        self.d.get(_url("@#$%INVALID!"))
        _wait_load(self.d)

        el = _find(self.d, "//*[contains(text(),'Verification Failed')]")
        assert el.is_displayed(), "Error not shown for invalid-format batch ID"

        timeline = self.d.find_elements(By.XPATH, "//*[contains(text(),'Supply Chain Journey')]")
        assert len(timeline) == 0, "Timeline must NOT appear for an invalid-format batch ID"


# ═════════════════════════════════════════════════════════════
#  TC-08-003: Verify Empty Batch ID Submission
#  TCOV: 08-003
# ═════════════════════════════════════════════════════════════
class TestTC08003:
    """
    Pre-conditions : User is on the traceability page.
    Post-conditions: No timeline rendered; page handles absent ID gracefully.

    Note: This app uses URL-based navigation — an 'empty' batch ID means
    navigating to /verify/ with no ID segment (Next.js 404 / redirect).
    """

    @pytest.fixture(autouse=True)
    def setup(self, driver):
        self.d = driver

    def test_no_batch_id_in_url_no_timeline(self):
        """TCON-08-003: /verify/ with no batch ID shows no timeline."""
        self.d.get(f"{BASE_URL}/verify/")
        time.sleep(2)

        timeline = self.d.find_elements(By.XPATH, "//*[contains(text(),'Supply Chain Journey')]")
        assert len(timeline) == 0, "Timeline must NOT appear when no batch ID is provided"

    def test_whitespace_batch_id_no_timeline(self):
        """TCON-08-003 variant: Whitespace-only batch ID shows no timeline."""
        self.d.get(_url("   "))
        _wait_load(self.d)

        timeline = self.d.find_elements(By.XPATH, "//*[contains(text(),'Supply Chain Journey')]")
        assert len(timeline) == 0, "Timeline must NOT appear for a whitespace-only batch ID"


# ═════════════════════════════════════════════════════════════
#  TC-08-004: Verify Incomplete Product History Display
#  TCOV: 08-006, 08-007, 08-015, 08-016, 08-019
# ═════════════════════════════════════════════════════════════
class TestTC08004:
    """
    Pre-conditions : INCOMPLETE_BATCH_ID exists but is missing one or more stages.
    Post-conditions: Timeline shown with missing stages labelled; warning visible.
    """

    @pytest.fixture(autouse=True)
    def setup(self, driver):
        self.d = driver

    def test_page_loads_for_incomplete_batch(self):
        """Page must not crash for a batch with incomplete history."""
        self.d.get(_url(INCOMPLETE_BATCH_ID))
        _wait_load(self.d)

        loaded = WebDriverWait(self.d, WAIT).until(
            lambda d: d.find_elements(By.CSS_SELECTOR, "h1, h2")
        )
        assert loaded, "Page crashed or did not load for an incomplete batch ID"

    def test_missing_stages_labelled_data_not_available(self):
        """TCON-08-015: Incomplete batch — only Harvesting stage present; Processing/Distribution absent.

        Actual app behaviour: the app renders only the stages that exist rather than
        labelling missing stages as 'Data Not Available'.  For a REGISTERED-only batch
        the Supply Chain Journey shows exactly one node (Harvesting); Processing and
        Distribution nodes must not appear.
        """
        self.d.get(_url(INCOMPLETE_BATCH_ID))
        _wait_load(self.d)
        time.sleep(2)  # allow React Flow canvas to finish rendering

        # For a REGISTERED-only batch the flowchart has exactly one node (Harvesting).
        # Processing and Distribution stage nodes must not appear anywhere on the page.
        later_stages = self.d.find_elements(
            By.XPATH,
            "//*[contains(text(),'Processing') or contains(text(),'Distribution')]",
        )
        visible_later = [
            el for el in later_stages
            if el.is_displayed()
            and el.tag_name in ("div", "p", "span", "text", "tspan")
            and ("Processing" in el.text or "Distribution" in el.text)
        ]
        assert len(visible_later) == 0, (
            "Incomplete (REGISTERED) batch should NOT show Processing or Distribution "
            "stage nodes — those stages have not occurred yet"
        )

    def test_incomplete_traceability_warning_shown(self):
        """TCON-08-016: 'REGISTERED' status visible — communicates the batch is incomplete.

        Actual app behaviour: incomplete batches display their current status
        ('REGISTERED') in the Product Details panel rather than a freeform warning
        message.  REGISTERED is the app's signal that the supply chain is not complete.
        """
        self.d.get(_url(INCOMPLETE_BATCH_ID))
        _wait_load(self.d)

        status = self.d.find_elements(
            By.XPATH,
            "//*["
            "contains(text(),'REGISTERED') or "
            "contains(text(),'incomplete') or "
            "contains(text(),'In Progress')"
            "]",
        )
        assert len(status) > 0, (
            "Incomplete batch must show 'REGISTERED' status (or equivalent) on the page "
            "to communicate that the supply chain is not yet complete"
        )


# ═════════════════════════════════════════════════════════════
#  TC-08-005: Verify Traceability Page UI Elements
#  TCOV: 08-008, 08-009
# ═════════════════════════════════════════════════════════════
class TestTC08005:
    """
    Pre-conditions : Logged in as Retailer; navigated to the traceability page.
    Post-conditions: Core UI elements present and functional.

    Note: The app uses URL navigation rather than a form-based batch ID entry.
    TCON-08-008 → batch ID visible in page body.
    TCON-08-009 → Supply Chain Journey section rendered and interactive.
    """

    @pytest.fixture(autouse=True)
    def setup(self, driver):
        self.d = driver

    def test_page_loads_successfully(self):
        """Page loads and a top-level heading is visible."""
        login_as_retailer(self.d)
        self.d.get(_url(VALID_BATCH_ID))
        _wait_load(self.d)

        heading = WebDriverWait(self.d, WAIT).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "h1"))
        )
        assert heading.is_displayed(), "Page did not load — no h1 heading found"

    def test_batch_id_visible_on_page(self):
        """TCON-08-008: Batch ID is shown on the page (breadcrumb or heading).

        Implementation note: JSX renders 'Batch #{batchId}' as two separate DOM text
        nodes ('Batch #' + the ID value).  XPath text() only matches the FIRST text
        node, so contains(text(), BATCH_ID) silently fails.  We search page_source
        instead, which is reliable for any rendering pattern.
        """
        login_as_retailer(self.d)
        self.d.get(_url(VALID_BATCH_ID))
        _wait_load(self.d)

        assert VALID_BATCH_ID in self.d.page_source, (
            f"Batch ID '{VALID_BATCH_ID}' is not present anywhere on the page"
        )

    def test_supply_chain_section_rendered_and_interactive(self):
        """TCON-08-009: Supply Chain Journey section renders; toggle buttons are clickable."""
        login_as_retailer(self.d)
        self.d.get(_url(VALID_BATCH_ID))
        _wait_load(self.d)

        section = _find(self.d, "//*[contains(text(),'Supply Chain Journey')]")
        assert section.is_displayed(), "Supply Chain Journey section is not rendered"

        toggles = self.d.find_elements(
            By.XPATH,
            "//button[contains(text(),'Flowchart') or contains(text(),'List View')]",
        )
        assert len(toggles) >= 1, "View-toggle buttons not found in Supply Chain section"
        toggles[0].click()


# ═════════════════════════════════════════════════════════════
#  TC-08-006: Error Guessing — Security and Edge Cases
#  TCOV: 08-020, 08-021, 08-022, 08-023, 08-024
# ═════════════════════════════════════════════════════════════
class TestTC08006:
    """
    Pre-conditions : User is on the traceability page.
    Post-conditions: No crash, no data leakage, no script execution.
    """

    @pytest.fixture(autouse=True)
    def setup(self, driver):
        self.d = driver

    def test_whitespace_only_batch_id(self):
        """TCON-08-020: Whitespace-only batch ID — no timeline rendered."""
        self.d.get(_url("   "))
        _wait_load(self.d)

        timeline = self.d.find_elements(By.XPATH, "//*[contains(text(),'Supply Chain Journey')]")
        assert len(timeline) == 0, "Timeline must NOT appear for whitespace-only batch ID"

    def test_sql_injection_no_data_exposed(self):
        """TCON-08-021: SQL injection pattern — no data returned, no crash."""
        self.d.get(_url("' OR '1'='1"))
        _wait_load(self.d)

        assert self.d.title is not None, "Page crashed on SQL injection input"

        timeline = self.d.find_elements(By.XPATH, "//*[contains(text(),'Supply Chain Journey')]")
        assert len(timeline) == 0, "No data should be returned for SQL injection batch ID"

    def test_xss_script_not_executed(self):
        """TCON-08-022: XSS <script> tag in batch ID — alert must NOT fire."""
        self.d.get(_url("<script>alert('xss')</script>"))
        _wait_load(self.d)

        try:
            alert = self.d.switch_to.alert
            alert_text = alert.text
            alert.dismiss()
            pytest.fail(f"XSS executed — alert appeared with: '{alert_text}'")
        except Exception:
            pass  # No alert = XSS correctly blocked

        assert self.d.title is not None, "Page crashed on XSS payload"

    def test_excessively_long_batch_id(self):
        """TCON-08-023: 500-character batch ID — no crash, no timeline."""
        self.d.get(_url("A" * 500))
        _wait_load(self.d)

        assert self.d.title is not None, "Page crashed on a 500-character batch ID"
        assert "500" not in self.d.title, "Server 500 error on long batch ID"

        timeline = self.d.find_elements(By.XPATH, "//*[contains(text(),'Supply Chain Journey')]")
        assert len(timeline) == 0, "No data should be returned for an excessively long batch ID"

    def test_rapid_repeated_navigation(self):
        """TCON-08-024: Navigate to the same verify URL 5 times rapidly — no crash."""
        url = _url(VALID_BATCH_ID)

        for _ in range(5):
            self.d.get(url)
            time.sleep(0.3)

        _wait_load(self.d)

        assert self.d.title is not None, "Page became unstable after rapid repeated navigation"
        assert "500" not in self.d.title, "Server error after rapid repeated navigation"
